### ISSUE TITLE
`Github代码` + `产物发布` + `Github Releases` 的最佳实践

### ISSUE THREAD

**Issue by zanminkian** [zanminkian/zanminkian.github.io#9]
## 对于单体仓库
单体仓库，即仓库内只有一个模块（或应用、或npm包）。考虑使用[changelogithub](https://github.com/antfu/changelogithub)。

### 示例
在项目根目录创建文件夹`.github/workflows`，然后在该文件夹内创建`release.yml`文件。

```yaml
name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: zengmingjian/code-server
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release:
    needs: output
    runs-on: ubuntu-latest
    permissions:
      contents: write # 如果没有这个权限将不能创建Github Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

上面示例中，`output` job用于将产物推送到docker hub。可以将上面的`output` job替换成其他的目标，比如编译项目然后发布到npm。

### 效果
1. 照常编写代码，不断将代码推送或者合并到主分支。
2. 当你想要发布一个版本，在主分支某个节点上打一个tag，例如`git tag v1.0.0 && git push --tag`。
3. 这时，github的workflow启动，会串行执行output和release阶段，将编译产物推送到远端，然后创建一个`Github Release`。

### 优缺点
- 优点：简单易用，支持所有单体仓库（不论是发布到npm、还是dockerhub、抑或是vscode扩展市场）。
- 缺点：Github Release只有`feat`、`fix`和`perf`类型的变更会被记录。

## 对于Monorepo
Monorepo， 前端（或Node）很流行的代码管理方案，是指一个代码仓库有多个模块（或应用、或npm包）。因为每个包（或应用）的版本号各不相同，比如改动`lib1`的代码应该只发布`lib1`包，其他包无需发布，这时`lib1`包的版本号就会变大，其他包不用变。这类仓库考虑使用[changsets](https://github.com/changesets/changesets)生态。

### 示例
以pnpm管理monorepo为例。
1. 首先，你的github要做两个预先的配置：`Settings` -> `Actions` -> `General`，勾选`Allow GitHub Actions to create and approve pull requests`；以及`Settings` -> `Secrets and variables` -> `Actions`，配置NPM_TOKEN。
2. 你的项目根必须安装`@changesets/cli`，执行`pnpm i @changesets/cli -Dw`以安装。
3. 然后执行`pnpm changeset init`在项目根目录初始化`.changeset`文件夹。`.changeset`文件夹里面的`config.json`配制成`{"baseBranch": "master"}`即可（如果你的主分支是`master`的话）。如果发布到公共npm则还要额外添加`"access": "public"`。`.changeset`文件夹内其他文件都可以删掉。
4. 项目根目录创建文件夹`.github/workflows`，然后在该文件夹内创建`release.yml`文件。
```yaml
name: Release

on:
  push:
    branches:
      - main
      - prerelease

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js Env
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: corepack enable && pnpm i

      - name: Create Release Pull Request or Publish
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: release"
          title: "chore: release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

#### 注意点
a子包使用另一个b子包，a的`package.json`的`dependencies`内应该`"b":"^1.0.0"`或者`"b":"workspace:^"`这种方式写，不要`"b":"*"`

### 效果
1. 如果你直接提交代码到主分支，改动的代码写完后，准备提交前需要执行`pnpm changeset`，然后填写资料，然后changsets会自动帮你在`.changeset`文件夹内新增一个markdown文件，这个md文件和你改动的代码一起提交到主分支。
2. 如果是别人的提交的MR到主分支，步骤和1类似。生成的md要和改动的代码一起提交上来。
3. 每次远程的主分支代码变更，github都会执行上面workflow。分两种情况：
   - 如果是改动主分支代码，`changesets/action`会创建一个自动创建一个MR，每次主分支改动会修改这次MR。这个MR如果被合并，就会触发下面这种情况。
   - 不是改动主分支代码，而是发版。这个发版其实就是删除掉所有`.changeset`文件夹内的所有md文件，然后相关的包的版本号都会遵循语以化版本规则进行修改（即版本号增加）。然后将版本号升级了的包发布到npm。

### 优缺点
- 优点：对于monorepo仓库可以让子包版本分别升级。
- 缺点：繁琐，每次代码变更都需要执行`pnpm changeset`并将记录变更的md文件提交。仅支持发布到npm，否则会有bug，原因是`changesets/action`只能支持发布到npm。
